# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7
  - 3.6

# Command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
- pip install -U tox-travis

addons:
  apt_packages:
    - pandoc

script:
- tox

after_success:
- pip install codecov
- codecov
- pip install Sphinx==3.0.3
- pip install sphinx_rtd_theme==0.4.3
- pip install .  # Seems to be required for the apidocs
- pip install nbsphinx
- pip install pandoc
- pip install ipykernel
- cd docs
- sphinx-apidoc ../bouter -o source/
- make html
- cd ..

# Assuming you have installed the travis-ci CLI tool, after you
# create the Github repo and add it to Travis, run the
# following command to finish PyPI deployment setup:
# $ travis encrypt --add deploy.password
deploy:
  - provider: pages
    skip_cleanup: true
    keep_history: true
    github_token:
        secure: 4vdK8iewZRXpOI/2SrLWFY5LHH2OyHRsnmTFB11HV/A4n47iDr0tsxF+w8xQmZAZm9iAf1jumduP8ajoM+o6gJ91LU65m2l//WZC5kz1ysEwmy9iartgtgbYUNZIQXI2zN2dvhZDRXu6Q1rMb7Ve6ZX1iNhKdvaLVkZSz4Na5jlgEicLNTNft2eoU6xSEjFhIDgsH/HkmU+CftHeJT3/uekgg6KYsqJRizipR2vrhx0/XAOtWXcfz65+77MeEji6pS+kZEvOCNiGA3mBhXBoRzrjiDfEolQAbVlHGozwuSasQxKqB1B8ooIZG0NdjcAWNpKEi+rGOfLr5qfr6MO30CQ+9er6qxmp4XSUfGCczLy4wOVhxfqKI7RVVSQ7abxTHWTBSfAKLYUGwH77FW2TrFfqeBbRz7L4QYZQB7WtgN0s+LZHaU5Xo6ci/hCr4UGOcDqH4lTWmw00YnwbP9OYLxxRdiQJawatG29gyIsVHxtqXdrqeBnZhQf9E2JOe5m2QXjGsVDF6a0/vd5mioWsj7/3x2GSqQOR+WU97qIRCDfc1S0RDB9ehmz/Qnncbgl7j7iud6cjZwqnpNyM1dLUfSDqfEdJLI85g1379ifPcA469e8W9l5LLFFTHj5S7lkONZLqHdQZ/q4cHnOpCOZPWpanpLT2aPynmoq/Kz3SvKo=
    on:
      branch: master
      python: 3.8
    local-dir: docs/_build/html

  - provider: pypi
    skip_cleanup: true
    distributions: sdist bdist_wheel
    user: __token__
    password:
        secure: "WF9apZHztLe8VjSF4t3lz9NmWfVOZl8082HXIm64MDj8QIhpFuQLBw9cMpZVf1nBXyuanJBwy5FTSXQxEYfqZSrzMkp5tb2S2JwygYYC1xfIILCRawJepWShsR8MCnS0YT12kgZ7esqVxjxjXN7oKrnF0DHHyNpsoNV/pY97L8J4a/Fs1Z1lwhUuotCE2EhK2jDNvl2jKofxmsf9oiTH5gtMHa8yfaRZURye3wjxDbtXK88qH1wxjUi1i0UGjnrzbpwP17CTggK0CjKj248oq7cRcPRC6Vj/NOfa1rLjrkIgY3PDVe2k/7wBuu0FM8VAoHIElGd4y0qwDg4lLn0gv0T3LWM7zzoOx+Uu8AXIu67p0ADV/bJzWL0jaTHBq7J7q6a1zMNCq550mr5m/phgIMr8JH9XwzvTFXsBMokxe1L9WDQ0B/pUFb5Kk5b8gAqQ4XBzFbZB/3cwbKSsEL99RKCwFnPg/GTqBDEWPTw7vv/mIrP/aLEHoCgo+RX5e7S809wgvgvtsFyw/3jXzlVtZxp8EMJCEvBU5hqyT1UNhFKvGSgaDu1jihi1CZyFJBE5iJy+r0O/wY+ckEisbcgtvG8w46hWBIR/6/CPuYxNJo6Dlt2I2PpTdMoaMiquKPh/ioV7WvdhezRHk1VTEnooIURrXtXOe+0t6RkwieNgzSk="
    on:
      tags: true
      branch: master
      python: 3.8
    skip_existing: true
    committer-from-gh: true
